export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR';
export const ALLOCATE_ELEMENT_FOR_COMMENTS_BLOCK_IN_STATE = 'ALLOCATE_ELEMENT_FOR_COMMENTS_BLOCK_IN_STATE';